# Generated by Django 4.2.4 on 2023-08-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_author_options_alter_demography_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='manga',
            field=models.FileField(default=1, upload_to='manga_pdf'),
            preserve_default=False,
        ),
    ]
